export type User = {
  name: string;
  email: string;
  phone: string;
  region: string;
  age: number;
};

export const users: User[] = [
  {
    name: "Geoffrey Thomas",
    email: "donec.luctus@protonmail.couk",
    phone: "1-239-845-1227",
    region: "Valle d'Aosta",
    age: 23,
  },
  {
    name: "Cyrus Stanley",
    email: "lorem.vehicula.et@protonmail.ca",
    phone: "(539) 562-2692",
    region: "Metropolitana de Santiago",
    age: 23,
  },
  {
    name: "Oleg Potts",
    email: "elit.elit.fermentum@aol.net",
    phone: "1-934-547-4862",
    region: "Mpumalanga",
    age: 49,
  },
  {
    name: "Hayden Browning",
    email: "in.sodales@icloud.net",
    phone: "(451) 152-0387",
    region: "Cordillera Administrative Region",
    age: 46,
  },
  {
    name: "Hope Rush",
    email: "ante.ipsum@protonmail.couk",
    phone: "(623) 653-8679",
    region: "Western Cape",
    age: 26,
  },
  {
    name: "Marcia Davis",
    email: "nisi.sem@outlook.couk",
    phone: "(656) 578-1870",
    region: "Luxemburg",
    age: 32,
  },
  {
    name: "Ava Cunningham",
    email: "mauris@protonmail.edu",
    phone: "(655) 881-4732",
    region: "Luik",
    age: 27,
  },
  {
    name: "Darrel Shepard",
    email: "rhoncus.nullam.velit@outlook.net",
    phone: "(685) 417-5877",
    region: "Hatay",
    age: 36,
  },
  {
    name: "Dorothy Benjamin",
    email: "semper@icloud.ca",
    phone: "1-600-586-4079",
    region: "Arica y Parinacota",
    age: 40,
  },
  {
    name: "Oleg Jennings",
    email: "commodo.hendrerit@aol.edu",
    phone: "(474) 815-3038",
    region: "Sindh",
    age: 38,
  },
  {
    name: "Ignacia Underwood",
    email: "nisl@aol.ca",
    phone: "1-679-465-5438",
    region: "Samsun",
    age: 44,
  },
  {
    name: "Cruz Nixon",
    email: "nibh.donec.est@protonmail.edu",
    phone: "(214) 476-8624",
    region: "Eastern Cape",
    age: 24,
  },
  {
    name: "Marah Wall",
    email: "lobortis.tellus@icloud.com",
    phone: "1-312-875-4864",
    region: "Quebec",
    age: 42,
  },
  {
    name: "Ira Clay",
    email: "elit.etiam.laoreet@protonmail.com",
    phone: "1-563-674-8770",
    region: "Metropolitana de Santiago",
    age: 37,
  },
  {
    name: "Kirsten Rutledge",
    email: "parturient@icloud.edu",
    phone: "(165) 767-5816",
    region: "Loreto",
    age: 49,
  },
  {
    name: "Ivan Holder",
    email: "aliquam@google.net",
    phone: "(284) 884-7824",
    region: "Alajuela",
    age: 31,
  },
  {
    name: "Lillian Brewer",
    email: "pretium.neque.morbi@icloud.couk",
    phone: "(793) 228-7374",
    region: "Cần Thơ",
    age: 46,
  },
  {
    name: "Brett Fowler",
    email: "nibh.phasellus@aol.couk",
    phone: "1-734-319-1318",
    region: "Salzburg",
    age: 23,
  },
  {
    name: "Angelica Woodward",
    email: "at.sem@outlook.ca",
    phone: "(215) 147-7662",
    region: "North Jeolla",
    age: 39,
  },
  {
    name: "Jason Lawrence",
    email: "aliquam.erat@aol.net",
    phone: "1-177-441-7123",
    region: "North Jeolla",
    age: 37,
  },
  {
    name: "Rina Pearson",
    email: "neque.vitae@aol.org",
    phone: "1-856-627-7915",
    region: "Junín",
    age: 36,
  },
  {
    name: "Carter Wilson",
    email: "cras.interdum.nunc@protonmail.ca",
    phone: "(291) 342-9095",
    region: "Alaska",
    age: 35,
  },
  {
    name: "Samuel Malone",
    email: "orci@outlook.edu",
    phone: "(658) 606-8367",
    region: "South Island",
    age: 45,
  },
  {
    name: "Matthew Barr",
    email: "tristique.aliquet@hotmail.net",
    phone: "1-287-145-7584",
    region: "Arequipa",
    age: 33,
  },
  {
    name: "Tanek Carrillo",
    email: "vitae@aol.org",
    phone: "(728) 398-5426",
    region: "Rheinland-Pfalz",
    age: 38,
  },
  {
    name: "Lucy Ferrell",
    email: "malesuada.augue.ut@hotmail.couk",
    phone: "(545) 768-1066",
    region: "Los Lagos",
    age: 41,
  },
  {
    name: "Jared Hurst",
    email: "nunc@aol.couk",
    phone: "1-633-883-9578",
    region: "Biobío",
    age: 35,
  },
  {
    name: "Skyler Flores",
    email: "ut@protonmail.ca",
    phone: "1-429-862-3875",
    region: "Berlin",
    age: 37,
  },
  {
    name: "Nathaniel Martin",
    email: "dapibus@hotmail.edu",
    phone: "(683) 142-2374",
    region: "North-East Region",
    age: 38,
  },
  {
    name: "Irma Cline",
    email: "sociis@hotmail.net",
    phone: "(414) 287-2851",
    region: "Castilla y León",
    age: 38,
  },
  {
    name: "Odessa Moran",
    email: "imperdiet.erat@google.net",
    phone: "1-838-412-2561",
    region: "Viken",
    age: 34,
  },
  {
    name: "Noelani Duffy",
    email: "vivamus.molestie@icloud.ca",
    phone: "1-324-512-1736",
    region: "Mersin",
    age: 24,
  },
  {
    name: "Jack Golden",
    email: "nisi.sem.semper@icloud.ca",
    phone: "(471) 650-5564",
    region: "Lower Austria",
    age: 23,
  },
  {
    name: "Omar Walker",
    email: "sed.consequat@protonmail.couk",
    phone: "(972) 357-6628",
    region: "Mizoram",
    age: 21,
  },
  {
    name: "Caesar Terry",
    email: "luctus.ipsum@outlook.com",
    phone: "(478) 321-6482",
    region: "Chocó",
    age: 35,
  },
  {
    name: "Graham Byers",
    email: "massa.mauris.vestibulum@protonmail.edu",
    phone: "(308) 678-1646",
    region: "Van",
    age: 34,
  },
  {
    name: "Kerry Williamson",
    email: "nec.urna@aol.com",
    phone: "1-569-541-5130",
    region: "Irkutsk Oblast",
    age: 21,
  },
  {
    name: "Maxine Evans",
    email: "elit.pharetra.ut@protonmail.org",
    phone: "1-694-542-4103",
    region: "Molise",
    age: 21,
  },
  {
    name: "Jael Rojas",
    email: "vitae.aliquet.nec@yahoo.ca",
    phone: "(475) 245-7452",
    region: "Basilicata",
    age: 45,
  },
  {
    name: "Yvette Orr",
    email: "lacus.etiam@outlook.couk",
    phone: "(568) 823-9116",
    region: "Warmińsko-mazurskie",
    age: 25,
  },
  {
    name: "Dara Bauer",
    email: "fusce.aliquet@google.ca",
    phone: "(846) 933-8601",
    region: "Sląskie",
    age: 48,
  },
  {
    name: "Ray Moon",
    email: "quam.pellentesque@protonmail.com",
    phone: "(424) 597-0172",
    region: "Rivne oblast",
    age: 45,
  },
  {
    name: "Basia Burton",
    email: "non.magna@hotmail.couk",
    phone: "(721) 402-6972",
    region: "Tamil Nadu",
    age: 31,
  },
  {
    name: "Colorado Alvarez",
    email: "bibendum@protonmail.ca",
    phone: "1-373-498-8126",
    region: "Ivano-Frankivsk oblast",
    age: 44,
  },
  {
    name: "Sara Mcbride",
    email: "augue.porttitor@yahoo.ca",
    phone: "(112) 973-4954",
    region: "Manitoba",
    age: 32,
  },
  {
    name: "Plato Marshall",
    email: "sed.orci@google.com",
    phone: "(389) 714-0781",
    region: "Zuid Holland",
    age: 47,
  },
  {
    name: "Quintessa Aguilar",
    email: "commodo.at@outlook.net",
    phone: "1-183-363-4013",
    region: "Prince Edward Island",
    age: 26,
  },
  {
    name: "Sarah Garrison",
    email: "cursus@protonmail.edu",
    phone: "1-327-847-3754",
    region: "South Island",
    age: 49,
  },
  {
    name: "Chandler Thomas",
    email: "dolor.sit.amet@hotmail.com",
    phone: "1-889-555-5302",
    region: "Arauca",
    age: 26,
  },
  {
    name: "Nash Graham",
    email: "urna.convallis@hotmail.couk",
    phone: "1-246-825-5772",
    region: "Oost-Vlaanderen",
    age: 38,
  },
];
